export const peopleData = [
  { name: "Alice Johnson", age: 28, email: "alice.johnson@example.com" },
  { name: "Bob Smith", age: 35, email: "bob.smith@example.com" },
  { name: "Charlie Brown", age: 22, email: "charlie.brown@example.com" },
  { name: "Daisy Miller", age: 30, email: "daisy.miller@example.com" },
  { name: "Ethan James", age: 27, email: "ethan.james@example.com" },
  { name: "Fiona Adams", age: 33, email: "fiona.adams@example.com" },
  { name: "George Clarke", age: 29, email: "george.clarke@example.com" },
  { name: "Hannah Lee", age: 24, email: "hannah.lee@example.com" },
  { name: "Ian Murphy", age: 42, email: "ian.murphy@example.com" },
  { name: "Jenna Scott", age: 26, email: "jenna.scott@example.com" },
  { name: "Kyle Reed", age: 31, email: "kyle.reed@example.com" },
  { name: "Laura Kim", age: 38, email: "laura.kim@example.com" },
  { name: "Mike Turner", age: 45, email: "mike.turner@example.com" },
  { name: "Nina Brooks", age: 36, email: "nina.brooks@example.com" },
  { name: "Oscar Martin", age: 34, email: "oscar.martin@example.com" },
  { name: "Paula Gonzalez", age: 23, email: "paula.gonzalez@example.com" },
  { name: "Quinn Baker", age: 40, email: "quinn.baker@example.com" },
  { name: "Rachel Cox", age: 29, email: "rachel.cox@example.com" },
  { name: "Sam Wallace", age: 25, email: "sam.wallace@example.com" },
  { name: "Tina Long", age: 37, email: "tina.long@example.com" },
];
